-- MySQL Script generated by MySQL Workbench
-- Wed Jul  5 23:16:42 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`medico` (
  `matricula` INT NOT NULL,
  `nombre` VARCHAR(30) NULL,
  `apellido` VARCHAR(30) NULL,
  `especialidad` VARCHAR(20) NULL,
  `observaciones` TEXT NULL,
  PRIMARY KEY (`matricula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`paciente` (
  `nss` BIGINT(20) NOT NULL,
  `nombre` VARCHAR(30) NOT NULL,
  `apellido` VARCHAR(30) NOT NULL,
  `domicilio` VARCHAR(50) NULL,
  `codigo_postal` SMALLINT(6) NULL,
  `telefono` VARCHAR(16) NULL,
  `nro_historial_clinico` INT NOT NULL,
  `observaciones` TEXT NULL,
  PRIMARY KEY (`nro_historial_clinico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ingreso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ingreso` (
  `id_ingreso` INT NOT NULL,
  `fecha_ingreso` DATE NOT NULL,
  `nro_habitacion` SMALLINT(6) NULL,
  `nro_cama` SMALLINT(6) NULL,
  `observaciones` TEXT NULL,
  `nro_historial_paciente` INT NULL,
  `matricula_medico` INT NULL,
  `medico_matricula` INT NOT NULL,
  `paciente_nro_historial_clinico` INT NOT NULL,
  PRIMARY KEY (`id_ingreso`),
  INDEX `fk_ingreso_medico_idx` (`medico_matricula` ASC) VISIBLE,
  INDEX `fk_ingreso_paciente1_idx` (`paciente_nro_historial_clinico` ASC) VISIBLE,
  CONSTRAINT `fk_ingreso_medico`
    FOREIGN KEY (`medico_matricula`)
    REFERENCES `mydb`.`medico` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ingreso_paciente1`
    FOREIGN KEY (`paciente_nro_historial_clinico`)
    REFERENCES `mydb`.`paciente` (`nro_historial_clinico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
